frontend/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, current_app
from frontend.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from flask_login import login_user, current_user, logout_user, login_required
import requests
import json
from frontend.models import User
from frontend import db


users = Blueprint('users', __name__)

@users.route('/register', methods = ['POST', 'GET'])
def normal_register():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    form = RegistrationForm()
    print(form.confirm_password.data)
    if form.validate_on_submit():
        print("Entered")
        request_response = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['NORMAL_REGISTER_URL'],
                                         json = {
                                             'name': form.name.data,
                                             'password': form.password.data,
                                             'email': form.email.data,
                                             'gt_id': form.gt_id.data
                                         })
        response = request_response.json()
        if response['status'] == 1:
            flash(f'Account created for {form.name.data}.', 'success')
            return redirect(url_for('users.login'))
        else:
            flash(response['error'], 'danger')
    print("Testing")
    return render_template('register.html', title = 'Register', form = form)

@users.route('/admin/register', methods = ['POST', 'GET'])
def admin_register():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    form = RegistrationForm()
    if form.validate_on_submit():
        request_response = requests.post(current_app.config['ENDPOINT_ROUTE'] + url_for('backend.users.admin_register'),
                                         json = {
                                             'name': form.name.data,
                                             'password': form.password.data,
                                             'email': form.email.data,
                                             'gt_id': form.gt_id.data
                                         })
        response = json.loads(request_response)
        if response['status'] == 1:
            flash(f'Account created for {form.name.data}.', 'success')
            return redirect(url_for('users.login'))
        else:
            flash(response['error'], 'danger')
    return render_template('register.html', title = 'Register', form = form)

@users.route('/login', methods = ['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        request_response = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['LOGIN_URL'],
                                         json={
                                             'email': form.email.data,
                                             'password': form.password.data,
                                         })
        response = request_response.json()
        if response['status'] == 1:
            user = User(response['id'], response['name'], response['email'], response['gt_id'], response['auth_token'])
            db.session.add(user)
            db.session.commit()
            print(User.query.filter_by(user_id=response['id']).order_by(User.id.desc()).first().auth_token)
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if response['isMaster']:
                return redirect(next_page) if next_page else redirect(url_for('dash.admin_dashboard'))
            elif response['isAdmin']:
                return redirect(next_page) if next_page else redirect(url_for('dash.dashboard'))
            else:
                return redirect(next_page) if next_page else redirect(url_for('dash.dashboard'))
        else:
            print("Unsuccessful")
            flash(response['error'], 'danger')
    return render_template('login.html', title = 'Login', form = form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash(f"You have logged out successfully.", 'success')
    return redirect(url_for('users.login'))

@users.route('/reset_password', methods = ['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    form = RequestResetForm()
    if form.validate_on_submit():
        request_response = requests.post(current_app.config['ENDPOINT_URL'] + url_for('backend.users.request_reset_password'),
                                          json = {
                                              'email': form.email.data
                                          })
        response = json.loads(request_response)
        if response['status'] == 1:
            flash(f"Please check your inbox for an email with instructions to reset the password.")
        else:
            flash(response['error'])
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title = "Request Reset Password", form = form)

@users.route('/reset/<token>', methods = ['GET', 'POST'])
def reset(token):
    if current_user.is_authenticated:
        return redirect(url_for('dash.dashboard'))
    request_response = requests.post(current_app.config['ENDPOINT_URL'] + url_for('backend.users.verify_reset_token'),
                                     json = {
                                         'token': token
                                     })
    response = json.loads(request_response)
    if response['status'] == 0:
        flash(response['error'], 'warning')
        return redirect(url_for('frontend.users.request_reset'))
    else:
        form = ResetPasswordForm()
        request_response = request.posts(current_app.config['ENDPOINT_URL'] + url_for('backend.users.reset_password'),
                                         json = {
                                             'token': token,
                                             'password': form.password.data
                                         })
        response = json.loads(request_response)
        if response['status'] == 1:
            flash(f'Your password has been reset.', 'success')
            return redirect(url_for('users.login'))
    return render_template('reset.html', title = "Reset Password", form = form)

@users.route('/check_in', methods = ['GET', 'POST'])
@login_required
def helper_check_in():
    request_data = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['HELPER_CHECK_IN_URL'],
                                 json={
                                     'auth_token': current_user.auth_token
                                 })
    data = request_data.json()
    if data['status'] == 0:
        flash(data['error'], 'danger')
        logout_user()
        return redirect(url_for('users.login'))
    elif data['status'] == 1:
        flash("Checked In Successfully!", 'success')
        return redirect(url_for('dash.dashboard'))

@users.route('/no_show', methods = ['GET', 'POST'])
@login_required
def helper_user_no_show():
    request_data = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['HELPER_NOT_FOUND_URL'],
                                 json={
                                     'auth_token': current_user.auth_token
                                 })
    data = request_data.json()
    if data['status'] == 0:
        flash(data['error'], 'danger')
        logout_user()
        return redirect(url_for('users.login'))
    elif data['status'] == 1:
        flash("User marked 'No Show'. You may now continue.", 'success')
        return redirect(url_for('dash.dashboard'))

@users.route('/helped', methods = ['GET', 'POST'])
@login_required
def helper_user_helped():
    request_data = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['HELPER_HELPED_URL'],
                                 json={
                                     'auth_token': current_user.auth_token
                                 })
    data = request_data.json()
    if data['status'] == 0:
        flash(data['error'], 'danger')
        logout_user()
        return redirect(url_for('users.login'))
    elif data['status'] == 1:
        flash("Awesome Job! You may now continue.", 'success')
        return redirect(url_for('dash.dashboard'))

@users.route('/users/sessions', methods = ['GET', 'POST'])
@login_required
def get_session_data_u():
    request_data = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['USER_SESSIONS_URL'],
                                 json={
                                     'auth_token': current_user.auth_token
                                 })
    data = request_data.json()
    if data['status'] == 0:
        flash(data['error'], 'danger')
        logout_user()
        return redirect(url_for('users.login'))
    elif data['status'] == 1:
        return render_template('user_sessions.html', title="Sessions | Helpify", sessions=data['data'])


@users.route('/admin/sessions', methods = ['GET', 'POST'])
@login_required
def get_session_data_a():
    request_data = requests.post(current_app.config['ENDPOINT_ROUTE'] + current_app.config['HELPER_SESSIONS_URL'],
                                 json={
                                     'auth_token': current_user.auth_token
                                 })
    data = request_data.json()
    if data['status'] == 0:
        flash(data['error'], 'danger')
        logout_user()
        return redirect(url_for('users.login'))
    elif data['status'] == 1:
        return render_template('helper_sessions.html', title="Sessions | Helpify", sessions=data['data'])

frontend/templates/helper_sessions.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Helpify</title>

    <!-- Bootstrap Core CSS -->
    <link href="../static/main/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../static/main/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../static/main/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../static/main/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Helpify</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{{ url_for('dash.dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Sessions<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ url_for('users.get_session_data_a') }}">All</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Account</a>
                        </li>
                        <li>
                            <a href="{{ url_for('users.logout') }}"><i class="fa fa-edit fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    {% with messages = get_flashed_messages(with_categories = true) %}
            	        {% if messages %}
	                        {% for category, message in messages %}
                	            <div class = 'alert alert-{{ category }}'>
	                                {{ message }}
	                            </div>
                            {% endfor %}
	                    {% endif %}
                    {% endwith %}
                    <h1 class="page-header">Sessions</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Topic</th>
                            <th scope="col">Requester</th>
                            <th scope="col">Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if sessions|length != 0 %}
                            {% for session in sessions %}
                                <tr>
                                    <th scope="row">{{ session['id'] }}</th>
                                    <td>{{ session['topic'] }}</td>
                                    <td>{{ session['requester'] }}</td>
                                    <td>{{ session['date'] }}</td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="4">No Data Available</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../static/main/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/main/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../static/main/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../static/main/dist/js/sb-admin-2.js"></script>

</body>

</html>

frontend/templates/helpers_online_a.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Helpify</title>

    <!-- Bootstrap Core CSS -->
    <link href="../static/main/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../static/main/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../static/main/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../static/main/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Helpify</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{{ url_for('dash.dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Sessions<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ url_for('users.get_session_data_a') }}">All</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Account</a>
                        </li>
                        <li>
                            <a href="{{ url_for('users.logout') }}"><i class="fa fa-edit fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    {% with messages = get_flashed_messages(with_categories = true) %}
            	        {% if messages %}
	                        {% for category, message in messages %}
                	            <div class = 'alert alert-{{ category }}'>
	                                {{ message }}
	                            </div>
                            {% endfor %}
	                    {% endif %}
                    {% endwith %}
                    <h1 class="page-header">Helpers Online</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Helper Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if helpers|length != 0 %}
                            {% for helper in helpers %}
                                <tr>
                                    <th scope="row">{{ helper['id'] }}</th>
                                    <td>{{ helper['name'] }}</td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="2">No Helpers Available</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../static/main/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/main/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../static/main/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../static/main/dist/js/sb-admin-2.js"></script>

</body>

</html>

frontend/templates/helpers_online_u.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Helpify</title>

    <!-- Bootstrap Core CSS -->
    <link href="../static/main/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../static/main/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../static/main/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../static/main/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Helpify</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{{ url_for('dash.dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Sessions<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ url_for('users.get_session_data_u') }}">All</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Account</a>
                        </li>
                        <li>
                            <a href="{{ url_for('users.logout') }}"><i class="fa fa-edit fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    {% with messages = get_flashed_messages(with_categories = true) %}
            	        {% if messages %}
	                        {% for category, message in messages %}
                	            <div class = 'alert alert-{{ category }}'>
	                                {{ message }}
	                            </div>
                            {% endfor %}
	                    {% endif %}
                    {% endwith %}
                    <h1 class="page-header">Helpers Online</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Helper Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if helpers|length != 0 %}
                            {% for helper in helpers %}
                                <tr>
                                    <th scope="row">{{ helper['id'] }}</th>
                                    <td>{{ helper['name'] }}</td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="2">No Helpers Available</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../static/main/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/main/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../static/main/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../static/main/dist/js/sb-admin-2.js"></script>

</body>

</html>